language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
before_install:
  - "git clone https://github.com/pmaupin/static_pdfs tests/static_pdfs"
install:
  - "pip install ."
  - "pip install reportlab || true"
  - "pip install zlib || true"
  - "pip install unittest2 || true"
# command to run tests
script: "cd tests; /usr/bin/env PYTHONPATH=. py.test"
